---
- hosts: testvm
  remote_user: root
  tasks:
  - name: Add Backports
    apt_repository: repo='deb http://http.debian.net/debian wheezy-backports main' state=present
  - name: Update kernel
    apt:  name=linux-image-amd64 state=latest default_release=wheezy-backports update_cache=yes
    # deb http://http.debian.net/debian wheezy-backports main
    #-apt: name=linux-image-amd64 state=latest default_release=wheezy-backports update_cache=yes
    #-name: Install xorg and fluxbox
    # apt: pgk=
